version: '3'
services:
    nginx:
        image: nginx:1.25.2-alpine3.18-slim
        container_name: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
    hst:
        # image: ${DOCKER_REGISTRY-}hst
        # container_name: hst   
        ports:
            - "5001-5003:80"
        build:
            context: .
            dockerfile: src/HSTService.Api/Dockerfile
        deploy:
            mode: replicated
            replicas: 3     
        depends_on:
            - nginx