version: '3'
services:
    nginx:
        image: nginx:1.25.2-alpine3.18-slim
        container_name: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
        depends_on:
            - hst1
            - hst2
    hst1:
        expose:
            - "80"
        hostname: hst1.docker
        build:
            context: .
            dockerfile: src/HSTService.Api/Dockerfile
    hst2:
        expose:
            - "80"
        hostname: hst2.docker
        build:
            context: .
            dockerfile: src/HSTService.Api/Dockerfile

    hst3:
        expose:
            - "80"
        hostname: hst3.docker
        build:
            context: .
            dockerfile: src/HSTService.Api/Dockerfile